# PlatformIO pre-script: make `git describe` available to the firmware as FW_VERSION.
#
# Wired in via `extra_scripts = pre:tools/git_version.py` in [env] (platformio.ini), so all envs
# get it. The string is what the portal dashboard shows, what pull-OTA compares against a Release
# manifest, and what ties a coredump back to a commit — see CLAUDE.md, "COMMIT BEFORE YOU BUILD".
#
# ⚠️ IT IS A GENERATED HEADER, NOT A -D FLAG, AND THAT IS THE WHOLE POINT. This used to do
# `env.Append(CPPDEFINES=[("FW_VERSION", ...)])`, which put the git hash on EVERY compile command
# in the tree. PlatformIO's build cache is SCons CacheDir, keyed on the full command line — so every
# commit changed the key of every object, and CI recompiled all 531 LVGL files, all 267 TFLM files
# and everything else on every push while reporting "Cache restored successfully" (measured
# 2026-09-08: 2698 objects for the jukebox, 1073 for sleep-machine, zero cache hits). Locally it was
# the mirror image: SCons does not treat a changed -D as a dependency, so the three files that USE
# the version kept their stale string across commits and had to be touched by hand.
#
# A header fixes both (warm-cache timings in PR #28, second pass). Only the three files that include "generated/fw_version.h" depend on it, so
# a new commit recompiles three objects and the cache serves the rest; and SCons sees the header
# change, so those three always carry the current string. The file is written only when its content
# changes, because rewriting an identical file would bump its mtime and recompile them for nothing.
import os
import subprocess

Import("env")  # noqa: F821 — provided by PlatformIO's SCons environment

try:
    rev = (
        subprocess.check_output(
            ["git", "describe", "--tags", "--always", "--dirty"],
            cwd=env["PROJECT_DIR"],
            stderr=subprocess.DEVNULL,
        )
        .decode()
        .strip()
    )
except Exception:
    rev = "unknown"

# include/ is on every env's include path by PlatformIO convention; include/generated/ is
# gitignored. The C string is quoted here (StringifyMacro is for -D flags, which escape differently).
out_dir = os.path.join(env["PROJECT_DIR"], "include", "generated")
out = os.path.join(out_dir, "fw_version.h")
content = (
    "// GENERATED by tools/git_version.py at build time — do not edit, do not commit.\n"
    "#pragma once\n"
    '#define FW_VERSION "%s"\n' % rev.replace("\\", "\\\\").replace('"', '\\"')
)
os.makedirs(out_dir, exist_ok=True)
old = None
if os.path.exists(out):
    with open(out) as f:
        old = f.read()
if old != content:
    with open(out, "w") as f:
        f.write(content)
print("[git_version] FW_VERSION = %s (%s)" % (rev, "written" if old != content else "unchanged"))
